============================= test session starts =============================
platform win32 -- Python 3.13.7, pytest-8.4.2, pluggy-1.6.0 -- C:\Dev\Gold3\.venv\Scripts\python.exe
cachedir: .pytest_cache
django: version: 5.2.6, settings: gchub_db.test_settings (from ini)
rootdir: C:\Dev\Gold3
configfile: pytest.ini
plugins: anyio-4.10.0, Faker-37.6.0, django-4.11.1
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
_______ ERROR collecting gchub_db/apps/xml_io/tests/jdf_reader_test.py ________
C:\Users\jacks\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
.venv\Lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
gchub_db\apps\xml_io\tests\jdf_reader_test.py:15: in <module>
    jdf_list = next(
E   StopIteration
=========================== short test summary info ===========================
ERROR gchub_db/apps/xml_io/tests/jdf_reader_test.py - StopIteration
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.51s ===============================
