============================= test session starts =============================
platform win32 -- Python 3.13.7, pytest-8.4.2, pluggy-1.6.0 -- C:\Dev\Gold3\.venv\Scripts\python.exe
cachedir: .pytest_cache
django: version: 5.2.6, settings: gchub_db.test_settings (from ini)
rootdir: C:\Dev\Gold3
configfile: pytest.ini
plugins: anyio-4.10.0, Faker-37.6.0, django-4.11.1
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
_____________________ ERROR collecting bin/email_test.py ______________________
bin\email_test.py:13: in <module>
    t = loader.get_template("emails/on_do_proof.txt")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.venv\Lib\site-packages\django\template\loader.py:19: in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
E   django.template.exceptions.TemplateDoesNotExist: emails/on_do_proof.txt
=========================== short test summary info ===========================
ERROR bin/email_test.py - django.template.exceptions.TemplateDoesNotExist: emails/on_do_proof.txt
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.61s ===============================
